In [3]:
import numpy as np

In [4]:
arr = np.random.randn(3, 4) * 2 + 4

In [12]:
arr

array([[-0.83647935,  5.39850007,  3.82021513,  6.25034405],
       [ 3.93977684,  2.77687692,  5.93343583,  5.54990105],
       [ 2.90583543,  3.83725788,  4.07323841,  4.5318158 ]])

In [10]:
print(f"{arr.min()=}\n{arr.max()=}\n{arr.std()=}\n{arr.mean()=}")

arr.min()=np.float64(-0.8364793547906659)
arr.max()=np.float64(6.250344054778192)
arr.std()=np.float64(1.8164269337790866)
arr.mean()=np.float64(4.015059836968263)


In [11]:
arr.reshape(4, 3)

array([[-0.83647935,  5.39850007,  3.82021513],
       [ 6.25034405,  3.93977684,  2.77687692],
       [ 5.93343583,  5.54990105,  2.90583543],
       [ 3.83725788,  4.07323841,  4.5318158 ]])

In [13]:
arr.T

array([[-0.83647935,  3.93977684,  2.90583543],
       [ 5.39850007,  2.77687692,  3.83725788],
       [ 3.82021513,  5.93343583,  4.07323841],
       [ 6.25034405,  5.54990105,  4.5318158 ]])